baseline: false
batch_size: 6
celeba_th: 0.3
center_crop: false
clip_gradients: 5
dataset: CUB
dataset_name: ~
dataset_root: "data/"
detach_k: false
eqv_border_padding: false
eqv_random_mirror: false
exp_name: ~
gpu: 0
gq: false
ignore_saliency_fg: false
ignore_small_parts: false
input_size: 256
kp_threshold: 6
lambda_bg: 10
lambda_contrastive: 2.3e3
lambda_eqv: 5.7e3
lambda_eqv_bg: 0
lambda_rgb: 3e1
lambda_variance: 0
lambda_sc: 5
layer_len: -1
learning_rate: 1e-05
learning_rate_w: 0.01
model: DeepLab50_2branch
model_type: new
momentum: 0.9
no_sal_masking: false
num_classes: 25
num_part_names: 4
num_parts: 4
num_steps: 100000
num_workers: 8
power: 0.9
pascal_class: car
random_mirror: false
random_scale: false
random_scale_high: 2.0
random_scale_low: 0.7
random_seed: 1234
ref_net: vgg19
ref_layer1: relu3_2
ref_layer2: relu5_4
ref_weight1: 0.33
ref_weight2: 1.0
ref_norm: false
restore_from: ~
save_pred_every: 5000
self_ref_coord: false
single_class: ~
snapshot_dir: runs
tb_dir: runs
temperature: .19
tps_mode: affine
tps_sigma: 0.01
unsup_mask: false
use_lab: true
vis_interval: 1000
vl: false
val_loss: 2
weight_decay: 0.0005
with_bg: False
hydra:
  run:
    dir: .
  output_subdir: null
